version: '3.8'
services:
  frontend:
    build: ./exambyte-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: backend-image
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
