package com.exambyte.entity;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

@Entity // Marks this class as a JPA entity, meaning it will be mapped to a database table.
@Data // Lombok annotation to automatically generate getters, setters, toString, equals, and hashCode methods.
public class Test {

    @Id // Marks this field as the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the primary key to be auto-generated by the database.
    private Long id; // Unique identifier for the Test entity.

    private String title; // Represents the title or name of the test.

    private LocalDateTime startTime; // Represents the date and time when the test starts.

    private LocalDateTime endTime; // Represents the date and time when the test ends.

    private LocalDateTime resultReleaseTime; // Represents the date and time when the test results will be released.

    @Column(columnDefinition = "TEXT") // Specifies that this field will be stored as a TEXT type in the database.
    private String questions; // Stores the questions for the test as a JSON string.
}
